server:
  port: 8080
  error:
    include-message: always
logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
spring:
  config:
    import: classpath:config.yml
app:
  jwt:
    secret: "12345678901234567890123456789012"
    expiry-minutes: 720 # 12 hours, should be enough
  security:
    public-paths:
      - /error
      - /state
      - /game
      - /game/status
      - /game/settings
      - /game/toggle-status
      - /player/join
    auth-pw: "oopygoopy"
    frontend: http://localhost:5173