server:
  port: 8080
  error:
    include-message: always
logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
spring:
  config:
    import: classpath:config.yml
app:
  jwt:
    secret: "12345678901234567890123456789012"
    expiry-minutes: 720 # 12 hours, should be enough
  security:
    public-paths:
      - /error
      - /game/health
      - /socket/**
      - /game/status
      - /game/settings
      - /player/join
      - /team/info/*
      - /api/push/**
    auth-pw: "a"
    frontend: http://localhost:5173
vapid:
  publicKey: BPBB7YTMuhbUbFEZZNXeNeTpw_lD3dobyzOiE7HUO7POfrMlEM-kztNoAnD2473B732jlD4agryajdOMKnRUiz8
  privateKey: 6OPI6pyL1dNgZSYpq2YgGfNbQFqS3_oQu1orG2a0OIg
  subject: mailto:moaesaycto@gmail.com