game:
  maxPlayers: -1
  minPlayers: 2
  minPlayersPerTeam: 1
  maxPlayersPerTeam: -1
  maxTeams: 2
  graceTime: 5 # 600 # 10 minutes
  scoutTime: 5 # 1800 # 30 minutes
  ffaTime: 5 # 1200 # 20 minutes
teams:
  - name: Yellow
    color: "#e1ff00"
  - name: Orange
    color: "#ff8300"
  - name: Pink
    color: "#ff00ee"